/* Generated By:JavaCC: Do not edit this line. NuevoParser201820Constants.java */
package uniandes.teolen.parserJavaCC.newParser201820;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NuevoParser201820Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int NEQ = 10;
  /** RegularExpression Id. */
  int LT = 11;
  /** RegularExpression Id. */
  int LTE = 12;
  /** RegularExpression Id. */
  int GTE = 13;
  /** RegularExpression Id. */
  int GT = 14;
  /** RegularExpression Id. */
  int INT = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int VAR = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int DEFINE = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int AND = 22;
  /** RegularExpression Id. */
  int OR = 23;
  /** RegularExpression Id. */
  int NAME = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\">\"",
    "<INT>",
    "<DIGIT>",
    "\"print\"",
    "\"var\"",
    "\"if\"",
    "\"define\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "<NAME>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
  };

}
