/* Generated By:JavaCC: Do not edit this line. ParserGConstants.java */
package uniandes.teolen.parserJavaCC.parserGrammars;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserGConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int MAY = 8;
  /** RegularExpression Id. */
  int MIN = 9;
  /** RegularExpression Id. */
  int RegI = 10;
  /** RegularExpression Id. */
  int RegD = 11;
  /** RegularExpression Id. */
  int DC = 12;
  /** RegularExpression Id. */
  int IC = 13;
  /** RegularExpression Id. */
  int NTerm = 14;
  /** RegularExpression Id. */
  int Term = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"::=\"",
    "<INT>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "\"RegI\"",
    "\"RegD\"",
    "\"DC\"",
    "\"IC\"",
    "<NTerm>",
    "<Term>",
    "\":\"",
    "\";\"",
    "\"$\"",
  };

}
